### ISSUE TITLE
(Documentation) Quick start code doesn't work

### ISSUE THREAD

**Issue by HQJaTu** [MarkoPaul0/WireBait#20]
**Describe the bug**
In the docs, there is an example snippet containing:
```
local dissector_tester = wirebait.plugin_tester.new({only_show_dissected_packets=true});
dissector_tester:dissectPcap("path_to_your_pcap_file.pcap");
```

**To Reproduce**
Run code as suggested.

**Expected behavior**
Working simulation of Wireshark.

**Additional context**
To get results, I do a:
```
local dissector_tester = wirebait.new({only_show_dissected_packets=true});
dissector_tester:dissectPcap("path_to_your_pcap_file.pcap");
```

Did the API change or am I missing something?
A simple text search for word `plugin_tester` yields absolutely nothing besides the example code.

**Comment by MarkoPaul0** [comment]
Hi HQJaTu,

Thank you for the detailed feedback. To be honest with you, it is very possible that I left the repo in a bad state (and given what you described it seems like it is the case).
I will have a look at it this weekend to try and fix things. I can't think of any reason why following the quick start guide would not work. It might be a case of outdated documentation.

**Comment by MarkoPaul0** [comment]
HQJaTu,

Once again I appreciate your feedback. My quick-start documentation was actually outdated. I have made the necessary updates so that following them should work now.

I have not been very productive with this project. I feel like it could be improved/extended greatly, but the thing is, I haven't seen a lot of interest/feedback. Regardless, please let me know if you have other issues, and if you have suggestions to make Wirebait more useful.

Cheers,

MarkoPaul0
