### ISSUE TITLE
[Question] How to add table for custom dissector

### ISSUE THREAD

**Issue by shaggygi** [MarkoPaul0/WireBait#22]
I recently came across this utility.  Very awesome 👍 

This is probably more of a Wireshark/Lua question, but what do you need to add to view bytes for a custom dissector using WireBait?

Using your demo_dissector.lua example, I can see all the bytes when using the following:

```
local udp_encap_table = DissectorTable.get("udp.port")
udp_encap_table:add(7437, alcxnet_protocol)
```

And when setting up my own dissector, it will dissect and display.  However, what if I'm going to use a serial port and there are only 4 bytes to dissect?  If I remove the udp table code, it will still dissect, but no bytes will show in output.

Any help is appreciated.

**Comment by MarkoPaul0** [comment]
Hi! 

The current version of Wirebait only supports the following stack: UDP/IP/Ethernet. When you are using the following lines of code:
```
local udp_encap_table = DissectorTable.get("udp.port")
udp_encap_table:add(7437, alcxnet_protocol)
```
you are essentially telling Wireshark (or Wirebait) that the dissector will be used to dissect UDP data. Without these lines, wirebait will not dissect anything because it only knows UDP. If you were to use this with a dissector that is not meant to dissect UDP data then it wouldn't work. There could be hacks were you could make it work by having your dissector pretend like it is parsing the protocol it wants even though it is getting UDP data. Again if you could make it work it would be a hack.

 I am not familiar with how communications work over serial ports so I cannot really help further. However, you are welcome to improve Wirebait, and if you want to become a contributor let me know! :)
