### ISSUE TITLE
Attempting to use `Field` object in Lua dissector results in error: `attempt to index a nil value (global 'Field')`

### ISSUE THREAD

**Issue by fabacab** [MarkoPaul0/WireBait#4]
Similar to issue #3, a Lua dissector plugin that attempts to use the `Field()` object from the Lua API (which, admittedly, is poorly documented) returns an error.

This command:

```sh
LUA_PATH="$HOME/src/WireBait/wirebait.lua;;" lua ~/src/ntalk-dissector/talk.lua 
```

produces this error output:

```
lua: $HOME/src/ntalk-dissector/talk.lua:72: attempt to index a nil value (global 'Field')
stack traceback:
        $HOME/src/ntalk-dissector/talk.lua:72: in local 'dofile_func'
        $HOME/src/WireBait/wirebait.lua:1659: in field 'new'
        $HOME/src/ntalk-dissector/talk.lua:17: in main chunk
        [C]: in ?
```

(`$HOME` is my home folder.)

The `talk.lua` script is [this Lua plugin dissector](https://github.com/meitar/ntalk-dissector).

(As per usual, let me know if this kind of feedback is welcome. I can stop creating issues here if it is not.)

**Comment by MarkoPaul0** [comment]
Hello meitar,

Thanks for your feedback, it is actually quite detailed and helpful. Your assessment of the issue is correct. The problem is when trying to access "Field", which for now is not supported by Wirebait. I'm gonna look into the API and see how long it would take to add that support.

Thanks again!

**Comment by MarkoPaul0** [comment]
Alright meitar,

I have added support for Fields. Now there are a few restrictions still:
- First, only fields defined in the dissector itself will work. In other words a field extractor for ip.src would not work right now. (The talk dissector only uses field extractors for "talk fields", so that's all good).
- Second, for now I have only addressed the problem within the scope of the issue you created. It turns out there is another "issue" which will prevent you from running the talk dissector. Rather than an actual issue it is again a lack of support. For now I have disabled the part of the dissector that required that support. The lines in questions are:

```lua
        -- TODO: Figure out what these last 8 bytes for a reply packet
        --       mean. Meanwhile fallback to generic "Data" dissector.
        Dissector.get('data'):call(
            tvbuf:range(
                address:offset() + address:len()
            ):tvb(), pktinfo, root
        )
```

If you need support for that feature as well, I would create another issue for it. In the meantime just comment them out and you'll be fine. The reason I didn't work on this is that it would require support for protocols not dissected by lua files, for which I would only be able to provide limited support anyways.

Please checkout the latest commit and let me know how things work for you :).

**Comment by fabacab** [comment]
I'm not in any particular rush to use Wirebait exclusively, I just wanted to try it out for a rapid prototyping project. :) If you make a mention of these limitations on the README for the project I'm sure it will prevent future confusion. Thanks again for the ambitious project.

**Comment by MarkoPaul0** [comment]
meitar,

As I said before, I have fixed the issue described in this ticket. I just recently went through a major refactoring and verified that wirebait worked on your sample pcaps with your ntalk dissector as long as the `Dissector.get('data'):call()` is disabled. I intend to make this feature available down the road for basic built-in dissectors such as "data".
The refactoring I just made should allow me to maintain and expand wirebait much more easily and efficiently.
If you have more comments, issues, suggestions, please do not hesitate to create other tickets as it will help me make this tool more useful.

Thanks a lot!
